# This is a basic workflow to help you get started with Actions

name: deploy_to_firebase_hosting

on:
  workflow_dispatch:
  push:
    tags: 
      - 'release-*'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      - name: Install dependencies
        run: | 
          npm config set "@fontawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" "${{ secrets.FONTAWESOME_NPM }}"
          npm ci

      - name: Build project
        run: npm run build:ci

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with: 
          name: deploy_dist
          path: dist
  
      - name: Deploy to firebase
        if: success()
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI }}
